<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEO2RDkh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEO2RDkh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEO2RDkh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEO2RDkh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEO2RDkh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EO2RDkh',
    'container.build_id' => '8871b234',
    'container.build_time' => 1652014918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEO2RDkh');
